### ISSUE TITLE
Since last upade, save state won't load

### ISSUE THREAD

**Issue by sergedc** [rafaelvcaetano/melonDS-android#1234]
* **Device model:** xiaomi 11t
* **Android version:** latest

**Problem:**  
Since last update on nov 2nd: open any rom, play for 1 minute, save state. Then when you load state, the emulator freezes. 
Note: loading state from previous versions seems to work, so the problem might not be with the load8ng but with the saving.

**Comment by jasongrrz** [comment]
Same problem here.

**Comment by rafaelvcaetano** [comment]
Thanks for the heads-up guys! Don't know how I didn't catch it. It should be fixed in the nightly release that's being generated (https://github.com/rafaelvcaetano/melonDS-android/actions/runs/6763938423). If everything is fine, I'll make a new release with the fix.

**Comment by uplush** [comment]
In the latest version on Plat Store, the state saving and loading function still does not work properly.

**Comment by rafaelvcaetano** [comment]
> In the test version on Play Store, the state saving and loading function still does not work properly.

I have not managed to reproduce the issue since the fix was released. Since the original problem was fixed, I'll close this ticket. If the problem is still happening for you, please open a new ticket with more information 🙂
