### ISSUE TITLE
new update problem

### ISSUE THREAD

**Issue by arklord13** [rafaelvcaetano/melonDS-android#1379]
* **Device model:** <p9lite 2016>
* **Android version:** <android 7>

**Problem:**  
games launch, but no image just sound and it quite after ~5s
Happens with all games, and they work with previous version.

**Comment by rafaelvcaetano** [comment]
Thanks for bringing attention to this! I've pushed a fix. Let me know if works for you.

**Comment by arklord13** [comment]
Hey! I tried the new update and still the same problem, it happens with all games and even when I boot the firmware, to be thorough I deleted the android data folder and tried again, still same result :/

**Comment by Fatcat2024-cpu** [comment]
Dont use opengl

**Comment by arklord13** [comment]
> Dont use opengl

I was not, but out of curiosity i tried it, exactly same results! 

After uninstalling and re installing, the app "remembered" the directory of the bios and the games, so i wonder if its not some settings that are "stuck" ? I'm stumped and just waiting an update that might solve this !

**Comment by Fatcat2024-cpu** [comment]
Sad to say kirin 650 is not powerfull enough even if @rafaelvcaetano can fix this you cannot enjoy playing because of lag..

**Comment by arklord13** [comment]
> Sad to say kirin 650 is not powerfull enough even if [@rafaelvcaetano](https://github.com/rafaelvcaetano) can fix this you cannot enjoy playing because of lag..

You would be surprised, ni no Kuni ran at 60, the spice and wolf game too, but then again Chrono trigger always had sound crackling. I hope it's okay if I say this but, I can already play DS games on drastic at full speed even with high resolution 3d rendering and an lcd shader applied, I realize it necessitate a lot of work (also let's be honest, my phone is OLD ) it's just that melonds in addition of getting better, has retroachievments, so it would be the perfect replacement of drastic.

**Comment by Fatcat2024-cpu** [comment]
I hope this year or next melonds opengl performance improved because drastic is dead and no longer active development 😔
Exophase abandon the best and fastest ds emulator on android
