### ISSUE TITLE
Can't load rom in redmi 5 plus

### ISSUE THREAD

**Issue by shabbirmahmud** [rafaelvcaetano/melonDS-android#45]
No rom loading in this emulator and the emulator is crashing.I am using corvus os custom rom and sleppy r11 kernel.This is the crashing log url-
https://del.dog/lefotipomi

![IMG_20210117_211204](https://user-images.githubusercontent.com/47573399/104847279-4872e880-5909-11eb-9e72-aa175e89ca26.jpg)
![IMG_20210117_211223](https://user-images.githubusercontent.com/47573399/104847286-5294e700-5909-11eb-8ae3-415052ed6016.jpg)
https://user-images.githubusercontent.com/47573399/104847407-ff6f6400-5909-11eb-9958-9e66caaf417c.mp4

**Comment by rafaelvcaetano** [comment]
Thanks for the detailed information. However, the build I uploaded does not allow me to analyse the stack trace you sent me. Could you install the version from the link below and send me the new crash log?

http://s000.tinyupload.com/?file_id=10936153351108951882

**Comment by shabbirmahmud** [comment]
> Thanks for the detailed information. However, the build I uploaded does not allow me to analyse the stack trace you sent me. Could you install the version from the link below and send me the new crash log?
> 
> http://s000.tinyupload.com/?file_id=10936153351108951882

As you told i downloaded the version and heres the new crash log url-
https://del.dog/cofotifaqy

**Comment by rafaelvcaetano** [comment]
Thanks. That really helps. It seems that the problem happens when initializing audio output. Now, this crash is easily fixable. I just didn't expect it to ever happen. And if initialization failed, this means that there would be no audio output. Do you have any sound problems in other apps? Do other users of that custom ROM have any sound problems? I'll update the sound lib since it's not updated since the project started. Maybe that will fix the problem.

**Comment by shabbirmahmud** [comment]
I guess not there is any issu in sound in that custom rom.Acctually the sound ic of that phone damaged.Thats why i cant hear any sound from any other apk.That is the reason.

**Comment by shabbirmahmud** [comment]
> I guess not there is any issu in sound in that custom rom.Acctually the sound ic of that phone damaged.Thats why i cant hear any sound from any other apk.So that is the reason.

**Comment by shabbirmahmud** [comment]
I connected my wireless headphone.Now the emulator is loading the rom.

**Comment by rafaelvcaetano** [comment]
So there seems to be something wrong with your phone. I'll mark this as a bug since the crash can be avoided, but the fix won't guarantee that you will have sound.

**Comment by Ankeraout** [comment]
Same problem here with my galaxy A51 5G, with the stock rom. I cannot start a game even with headphones plugged.
I have downloaded the version that is supposed to log the crash but can't find the log file.

**Comment by rafaelvcaetano** [comment]
The Beta 1.1.0 release should now fix this problem. Can you test it please?

**Comment by Ankeraout** [comment]
![Screenshot_20210215-083320_melonDS](https://user-images.githubusercontent.com/15966256/107917692-a0345c00-6f68-11eb-9374-ca72203649f9.jpg)
Still not for me

**Comment by shabbirmahmud** [comment]
> The Beta 1.1.0 release should now fix this problem. Can you test it please?

Yes.The problem is solved now.I can now load rom without external audio device.Its working perfectly now.

**Comment by rafaelvcaetano** [comment]
Is the sound also working?

**Comment by shabbirmahmud** [comment]
> Still not for me
I don't whats worng with ur phn.But you should give detailed information like 
1-bios files name
2-bios files directory(internel/externel)
I have a phn that cant load rom when bios directory is in external storage.
3-crash log file
4-system partition ss
And lastly i didn't saw any pokemon games have name pokemon diamant🤔.Maybe that rom is invalid..

**Comment by shabbirmahmud** [comment]
> Is the sound also working?

No,sound is not working.Bcz it is my phn's hardware problem.My phone's sound ic hardware is dameged.Thats why.The full phn sound is not working.

**Comment by rafaelvcaetano** [comment]
> No,sound is not working.Bcz it is my phn's hardware problem.My phone's sound ic hardware is dameged.Thats why.The full phn sound is not working.

I knew something was wrong :P

@Ankeraout please open a new issue since your problem is clearly different and we will try to fix it. I will now close this one since it's solved.

**Comment by shabbirmahmud** [comment]
> > No,sound is not working.Bcz it is my phn's hardware problem.My phone's sound ic hardware is dameged.Thats why.The full phn sound is not working.
> 
> I knew something was wrong :P
> 
> @Ankeraout please open a new issue since your problem is clearly different and we will try to fix it. I will now close this one since it's solved.

I don't think i should open a new issu regarding the sound.I can't hear any sound like youtube videos,game sounds.I have different phones.Its a side phn of mine.Its not necessary to solve the sound problem.I have to change the sound ic of my phn from a neaest service center.That will solve the sound problem.

**Comment by rafaelvcaetano** [comment]
@Ankeraout test the new Beta 1.1.1 version. If it shows a dialog asking if you want to open a GitHub issue, please do so.
